buildscript {
    ext {
        kotlin_version = '1.9.22'
        gradle_version = '8.2.1'
        java_version = JavaVersion.VERSION_17
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$gradle_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }

    plugins.withType(com.android.build.gradle.BasePlugin).configureEach {
        android {
            compileOptions {
                sourceCompatibility java_version
                targetCompatibility java_version
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
